[build]
buildCommand = "pnpm run build"

[build.environment]
BASE_PATH = "/crm/"

[deploy]
preDeployCommand = "pnpm run db:migrate"

[deploy.environment]
DATABASE_URL = "${{Postgres-BkOp.DATABASE_URL}}"
BASE_PATH = "/crm/"
