/**
 * Property test for Layout_JSON round-trip and persistence.
 *
 * Property 14: Layout_JSON round-trip and persistence.
 *
 * **Validates: Requirements 6.1, 6.2, 6.3, 6.4**
 *
 * Module under test:
 *   - Type `LayoutJson` from `@workspace/db`
 *   - `__test__.parseLayout` from `artifacts/api-server/src/lib/layoutPlanner.ts`
 *
 * Properties verified here:
 *   1. JSON.stringify → JSON.parse → parseLayout round-trip preserves
 *      structure for any LayoutJson generated by the smart arbitrary
 *      (Requirements 6.1, 6.4 — persistence as-is to `designs.layout_json` jsonb).
 *   2. JSONB-compatibility: every leaf is integer, string, or null —
 *      no Dates, Buffers, functions or fractional numbers (Requirement 6.4).
 *   3. Schema enforcement: `furniture.length ∈ [1..12]`, dimensional fields are
 *      integers in their declared ranges, `rotationDeg ∈ {0,90,180,270}`,
 *      `id` matches `^[a-z0-9_-]{1,32}$` (Requirements 6.2, 6.3).
 *   4. Window optionality: `parseLayout` accepts `window: null` and an
 *      explicit `{ wall, offsetCm, widthCm }`, but rejects an absent /
 *      `undefined` window (strict JSON schemas don't accept undefined,
 *      Requirement 6.1, 6.2).
 *   5. Field rejection: a LayoutJson with a numeric out of range (e.g.
 *      `room.widthCm = 999`) returns `null` from `parseLayout`
 *      (Requirements 6.2, 6.5).
 *
 * Run via Node's built-in test runner:
 *   pnpm --filter @workspace/api-server test
 */

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import fc from "fast-check";
import type { LayoutJson } from "@workspace/db";
import { __test__ } from "../../src/lib/layoutPlanner.js";

const { parseLayout } = __test__;

// ─── Generators ──────────────────────────────────────────────────────────────

const wallArb = fc.constantFrom("north", "east", "south", "west");

const furnitureTypeArb = fc.constantFrom(
  "bed",
  "wardrobe",
  "desk",
  "chair",
  "nightstand",
  "rug",
  "dresser",
  "shelf",
  "sofa",
  "armchair",
  "tv_unit",
  "coffee_table",
  "dining_table",
  "kitchen_island",
  "sink",
  "toilet",
  "bathtub",
  "shower",
  "mirror",
  "cabinet",
);

const roomTypeArb = fc.constantFrom(
  "bedroom",
  "kitchen",
  "bathroom",
  "living_room",
  "hallway",
  "nursery",
  "apartment",
);

// id must match `^[a-z0-9_-]{1,32}$` per the Layout_JSON schema.
// fast-check 4.x removed `fc.stringOf`; build the string from a constrained
// char arbitrary instead. fc.array(...).map(join) is the canonical replacement.
const idCharArb = fc.constantFrom(
  "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
  "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
  "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "_", "-",
);
const idArb = fc
  .array(idCharArb, { minLength: 1, maxLength: 32 })
  .map((chars) => chars.join(""));

const furnitureItemArb = fc.record({
  id: idArb,
  type: furnitureTypeArb,
  widthCm: fc.integer({ min: 20, max: 400 }),
  depthCm: fc.integer({ min: 20, max: 400 }),
  heightCm: fc.integer({ min: 10, max: 280 }),
  xCm: fc.integer({ min: 0, max: 800 }),
  yCm: fc.integer({ min: 0, max: 800 }),
  rotationDeg: fc.constantFrom(0, 90, 180, 270),
});

const layoutJsonArb: fc.Arbitrary<LayoutJson> = fc.record({
  room: fc.record({
    roomType: roomTypeArb,
    widthCm: fc.integer({ min: 200, max: 800 }),
    lengthCm: fc.integer({ min: 200, max: 800 }),
    heightCm: fc.integer({ min: 220, max: 350 }),
  }),
  door: fc.record({
    wall: wallArb,
    offsetCm: fc.integer({ min: 0, max: 800 }),
    widthCm: fc.integer({ min: 70, max: 110 }),
  }),
  window: fc.option(
    fc.record({
      wall: wallArb,
      offsetCm: fc.integer({ min: 0, max: 800 }),
      widthCm: fc.integer({ min: 60, max: 400 }),
    }),
    { nil: null },
  ),
  furniture: fc.array(furnitureItemArb, { minLength: 1, maxLength: 12 }),
}) as fc.Arbitrary<LayoutJson>;

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Recursively check that every leaf is integer/string/boolean/null.
 * Anything else (Date, Buffer, function, fractional number, undefined,
 * symbol) is *not* JSONB-compatible.
 */
function isJsonbCompatible(value: unknown): boolean {
  if (value === null) return true;
  if (typeof value === "string") return true;
  if (typeof value === "boolean") return true;
  if (typeof value === "number") return Number.isInteger(value);
  if (Array.isArray(value)) return value.every(isJsonbCompatible);
  if (typeof value === "object") {
    return Object.values(value as Record<string, unknown>).every(
      isJsonbCompatible,
    );
  }
  return false;
}

const FURNITURE_ID_RE = /^[a-z0-9_-]{1,32}$/;

const baselineValidLayout = (): LayoutJson => ({
  room: { roomType: "bedroom", widthCm: 300, lengthCm: 400, heightCm: 250 },
  door: { wall: "north", offsetCm: 50, widthCm: 90 },
  window: null,
  furniture: [
    {
      id: "bed1",
      type: "bed",
      widthCm: 160,
      depthCm: 200,
      heightCm: 50,
      xCm: 50,
      yCm: 50,
      rotationDeg: 0,
    },
  ],
});

// ─── Tests ───────────────────────────────────────────────────────────────────

describe("Layout_JSON Property 14: round-trip and persistence", () => {
  // -----------------------------------------------------------------------
  // Property 14.1 — round-trip preserves structure.
  // Validates: Requirements 6.1, 6.4
  // -----------------------------------------------------------------------
  it("JSON.stringify → JSON.parse → parseLayout returns deep-equal copy of the original", () => {
    fc.assert(
      fc.property(layoutJsonArb, (layout) => {
        const serialized = JSON.stringify(layout);
        const reparsed = JSON.parse(serialized);
        const result = parseLayout(reparsed);
        assert.notEqual(
          result,
          null,
          `parseLayout returned null for a valid generated layout: ${serialized}`,
        );
        // Compare against the post-serialization shape: that's what
        // postgres' jsonb column would actually round-trip. fast-check's
        // `fc.record` produces null-prototype objects, but JSONB always
        // round-trips to plain `Object`-prototyped values. Comparing
        // JSON-normalized inputs sidesteps the incidental prototype
        // difference and tests what we actually care about — value
        // identity.
        assert.deepStrictEqual(result, JSON.parse(serialized));
      }),
      { numRuns: 200 },
    );
  });

  // -----------------------------------------------------------------------
  // Property 14.2 — JSONB-compatibility.
  // Validates: Requirement 6.4
  // -----------------------------------------------------------------------
  it("every field is integer / string / null — no Dates, Buffers, functions, fractional numbers", () => {
    fc.assert(
      fc.property(layoutJsonArb, (layout) => {
        assert.equal(
          isJsonbCompatible(layout),
          true,
          `non-JSONB value detected: ${JSON.stringify(layout)}`,
        );
        const reparsed = JSON.parse(JSON.stringify(layout));
        const result = parseLayout(reparsed);
        assert.notEqual(result, null);
        assert.equal(isJsonbCompatible(result), true);
      }),
      { numRuns: 100 },
    );
  });

  // -----------------------------------------------------------------------
  // Property 14.3 — schema enforcement on the parseLayout output.
  // Validates: Requirements 6.2, 6.3
  // -----------------------------------------------------------------------
  it("parseLayout output respects all schema constraints", () => {
    fc.assert(
      fc.property(layoutJsonArb, (layout) => {
        const parsed = parseLayout(JSON.parse(JSON.stringify(layout)));
        assert.notEqual(parsed, null);
        if (parsed === null) return;

        // furniture.length ∈ [1..12]  (minItems: 1, maxItems: 12)
        assert.ok(
          parsed.furniture.length >= 1 && parsed.furniture.length <= 12,
          `furniture length out of [1..12]: ${parsed.furniture.length}`,
        );

        // room: integers in declared ranges
        assert.ok(Number.isInteger(parsed.room.widthCm));
        assert.ok(parsed.room.widthCm >= 200 && parsed.room.widthCm <= 800);
        assert.ok(Number.isInteger(parsed.room.lengthCm));
        assert.ok(parsed.room.lengthCm >= 200 && parsed.room.lengthCm <= 800);
        assert.ok(Number.isInteger(parsed.room.heightCm));
        assert.ok(parsed.room.heightCm >= 220 && parsed.room.heightCm <= 350);

        // door: integers in declared ranges
        assert.ok(Number.isInteger(parsed.door.offsetCm));
        assert.ok(parsed.door.offsetCm >= 0 && parsed.door.offsetCm <= 800);
        assert.ok(Number.isInteger(parsed.door.widthCm));
        assert.ok(parsed.door.widthCm >= 70 && parsed.door.widthCm <= 110);

        // window: object|null
        if (parsed.window !== null) {
          assert.ok(Number.isInteger(parsed.window.offsetCm));
          assert.ok(
            parsed.window.offsetCm >= 0 && parsed.window.offsetCm <= 800,
          );
          assert.ok(Number.isInteger(parsed.window.widthCm));
          assert.ok(
            parsed.window.widthCm >= 60 && parsed.window.widthCm <= 400,
          );
        }

        // furniture items: ranges + id pattern + rotation enum
        for (const item of parsed.furniture) {
          assert.ok(
            FURNITURE_ID_RE.test(item.id),
            `id "${item.id}" fails ${FURNITURE_ID_RE}`,
          );
          assert.ok(Number.isInteger(item.widthCm));
          assert.ok(item.widthCm >= 20 && item.widthCm <= 400);
          assert.ok(Number.isInteger(item.depthCm));
          assert.ok(item.depthCm >= 20 && item.depthCm <= 400);
          assert.ok(Number.isInteger(item.heightCm));
          assert.ok(item.heightCm >= 10 && item.heightCm <= 280);
          assert.ok(Number.isInteger(item.xCm));
          assert.ok(item.xCm >= 0 && item.xCm <= 800);
          assert.ok(Number.isInteger(item.yCm));
          assert.ok(item.yCm >= 0 && item.yCm <= 800);
          assert.ok(
            [0, 90, 180, 270].includes(item.rotationDeg),
            `rotationDeg ${item.rotationDeg} not in {0,90,180,270}`,
          );
        }
      }),
      { numRuns: 100 },
    );
  });

  // -----------------------------------------------------------------------
  // Property 14.4 — window optionality.
  // Validates: Requirements 6.1, 6.2
  // -----------------------------------------------------------------------
  it("accepts window: null", () => {
    const layout = baselineValidLayout();
    layout.window = null;
    const parsed = parseLayout(JSON.parse(JSON.stringify(layout)));
    assert.notEqual(parsed, null);
    assert.equal(parsed!.window, null);
  });

  it("accepts an explicit window object { wall, offsetCm, widthCm }", () => {
    const layout = baselineValidLayout();
    layout.window = { wall: "south", offsetCm: 100, widthCm: 120 };
    const parsed = parseLayout(JSON.parse(JSON.stringify(layout)));
    assert.notEqual(parsed, null);
    assert.deepStrictEqual(parsed!.window, {
      wall: "south",
      offsetCm: 100,
      widthCm: 120,
    });
  });

  it("rejects layouts where the `window` field is absent / undefined (strict schema)", () => {
    const baseline = baselineValidLayout();
    // window omitted entirely → JSON.stringify drops it, so this is the
    // same shape parseLayout would receive after a round-trip from a
    // server that forgot to write `window: null`.
    const malformed: Record<string, unknown> = {
      room: baseline.room,
      door: baseline.door,
      furniture: baseline.furniture,
      // window: undefined
    };
    const parsed = parseLayout(JSON.parse(JSON.stringify(malformed)));
    assert.equal(
      parsed,
      null,
      "parseLayout must reject layouts without an explicit window: null",
    );
  });

  // -----------------------------------------------------------------------
  // Property 14.5 — out-of-range numeric returns null.
  // Validates: Requirements 6.2, 6.5
  // -----------------------------------------------------------------------
  it("returns null when room.widthCm is out of [200..800]", () => {
    fc.assert(
      fc.property(
        fc.oneof(
          fc.integer({ min: -1000, max: 199 }),
          fc.integer({ min: 801, max: 100_000 }),
        ),
        (badWidth) => {
          const layout = baselineValidLayout();
          (layout.room as { widthCm: number }).widthCm = badWidth;
          const parsed = parseLayout(JSON.parse(JSON.stringify(layout)));
          assert.equal(
            parsed,
            null,
            `parseLayout must reject room.widthCm=${badWidth}`,
          );
        },
      ),
      { numRuns: 50 },
    );
  });

  it("returns null when furniture.length is 0 (below minItems)", () => {
    const layout = baselineValidLayout();
    (layout as { furniture: unknown[] }).furniture = [];
    const parsed = parseLayout(JSON.parse(JSON.stringify(layout)));
    assert.equal(parsed, null);
  });

  it("returns null when a furniture item has rotationDeg outside {0,90,180,270}", () => {
    fc.assert(
      fc.property(
        fc.integer({ min: -360, max: 360 }).filter(
          (r) => ![0, 90, 180, 270].includes(r),
        ),
        (badRot) => {
          const layout = baselineValidLayout();
          (
            layout.furniture[0] as { rotationDeg: number }
          ).rotationDeg = badRot;
          const parsed = parseLayout(JSON.parse(JSON.stringify(layout)));
          assert.equal(
            parsed,
            null,
            `parseLayout must reject rotationDeg=${badRot}`,
          );
        },
      ),
      { numRuns: 30 },
    );
  });
});
