import app from "./app";
import { db, pool, usersTable, voronkaColumnsTable, mastersTable, ordersTable, orderDispatchesTable, masterCheckinsTable } from "@workspace/db";
import { sql } from "drizzle-orm";
import { eq, inArray, and, lte, isNull } from "drizzle-orm";
import { hashPassword } from "./lib/auth.js";
import { bootstrapFirstAdmin } from "./lib/bootstrap-admin.js";
import { runDrizzleMigrations } from "./lib/migrate.js";
import { checkOverdueTransactions } from "./lib/orderEligibility.js";
import { performBroadcast } from "./lib/broadcastOrder.js";
import { broadcastCheckin, broadcastCheckinReminder } from "./lib/checkinBroadcast.js";
import { systemSettingsTable } from "@workspace/db";
import { sendMorningBriefing, checkStaleOrders, sendWeeklyReport, checkNewMarkets, runAutonomousCycle, runQuickAutonomousCheck } from "./managerBot.js";
import { autonomousAgent } from "./autonomousAgent.js";
import { runProactiveChecks } from "./lib/dispatcherAI.js";
import { checkResponseWindows } from "./lib/priorityAssign.js";
import { backfillReceiptTransactions } from "./routes/receipts.js";
import { runAvitoSchedule } from "./routes/avito.js";
import { runTemplateScenario } from "./routes/ai-office.js";
import { seedCommunityDemo, simulateCommunityActivity } from "./lib/communitySeed.js";

const port = Number(process.env["PORT"] || "8080");

if (Number.isNaN(port) || port <= 0) {
  throw new Error(`Invalid PORT value: "${process.env["PORT"]}"`);
}

// Runtime fixes that aren't expressible in the Drizzle schema and so are not
// generated by `drizzle-kit`. Everything else — CREATE TABLE, ALTER ADD COLUMN,
// CREATE TYPE, indexes that ARE in the schema — is owned by the baseline +
// future migrations under `lib/db/migrations/` and applied by
// `runDrizzleMigrations()`.
//
// Keep this list small. If something here can be expressed in the schema
// (e.g. via index().where() or .check()), prefer moving it there.
async function runRuntimeFixes() {
  // Hand-tuned partial / multi-column performance indexes that aren't in the schema yet.
  await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_orders_city_status ON orders(city, status) WHERE deleted_at IS NULL`);
  await db.execute(sql`CREATE INDEX IF NOT EXISTS idx_order_dispatches_order_status ON order_dispatches(order_id, status)`);

  // wallet_transactions indexes/constraints removed — table dropped (Phase C cleanup)

  // master_wallet token-balance constraint removed in Phase D — token model is closed.
  // Drop the legacy CHECK constraint if it still exists from older deploys.
  await db.execute(sql`
    DO $$ BEGIN
      IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'master_wallet_balance_check'
          AND conrelid = 'master_wallet'::regclass
      ) THEN
        ALTER TABLE master_wallet DROP CONSTRAINT master_wallet_balance_check;
      END IF;
    END $$
  `);

  // Re-sync ALL serial sequences to MAX(id) of their owned column.
  //
  // Why: legacy data imports inserted rows with explicit ids without bumping
  // the backing sequence (`*_id_seq`). A desynced sequence then hands out LOW,
  // already-used ids on the next INSERT — causing either PK-conflict errors OR
  // (after the original row was deleted) silent id REUSE, where a freshly
  // registered master inherits a deleted master's orders/dispatches/debt.
  // See the Виталий/Краснодар incident: masters_id_seq sat at 23 while
  // max(masters.id) was 85.
  //
  // This block is idempotent and never moves a sequence backwards
  // (GREATEST(max_id, current last_value)). Runs on every startup as a guard.
  await db.execute(sql`
    DO $$
    DECLARE
      r RECORD;
      maxid BIGINT;
    BEGIN
      FOR r IN
        SELECT s.relname AS seq, t.relname AS tbl, a.attname AS col
        FROM pg_class s
        JOIN pg_depend d ON d.objid = s.oid AND d.deptype = 'a'
        JOIN pg_class t ON t.oid = d.refobjid
        JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = d.refobjsubid
        JOIN pg_namespace n ON n.oid = s.relnamespace
        WHERE s.relkind = 'S' AND n.nspname = 'public'
      LOOP
        EXECUTE format('SELECT COALESCE(MAX(%I), 0) FROM public.%I', r.col, r.tbl) INTO maxid;
        IF maxid > 0 THEN
          EXECUTE format(
            'SELECT setval(%L, GREATEST(%s, (SELECT last_value FROM public.%I)), true)',
            r.seq, maxid, r.seq
          );
        END IF;
      END LOOP;
    END $$
  `);

  // Seed partner system settings (idempotent via ON CONFLICT).
  await db.execute(sql`
    INSERT INTO system_settings (key, value, updated_at) VALUES
      ('partner_fixed_salary_max',        '15000', NOW()),
      ('partner_fixed_target_leads',      '30',    NOW()),
      ('partner_bonus_per_accepted_lead', '250',   NOW()),
      ('partner_monthly_leads_plan',      '50',    NOW()),
      ('manual_partner_lead_review',      'true',  NOW()),
      ('partner_payout_day_start',        '1',     NOW()),
      ('partner_payout_day_end',          '5',     NOW())
    ON CONFLICT (key) DO NOTHING
  `);

  // ── ХочуТакже — гео-сообщество baseline (spec: hochu-takzhe-community) ──────
  // Эти таблицы описаны как Drizzle-схемы (lib/db/src/schema/{zhk,specialties,
  // community-*}.ts), но соответствующая drizzle-миграция НЕ сгенерирована,
  // поэтому `runDrizzleMigrations()` их не создаёт. До появления сгенерированной
  // миграции создаём/дополняем схему здесь идемпотентно (IF NOT EXISTS) — точная
  // копия artifacts/api-server/migrations/2026-01-20-community-baseline.sql.
  // Аддитивно и безопасно на работающем проде; повторный прогон — no-op.
  // ВАЖНО: если позже появится drizzle-миграция под эти таблицы — удалить этот
  // блок, чтобы `migrate()` не упал на `relation already exists`.
  await applyCommunityBaseline();

  // ── city-launch-model (spec: .kiro/specs/city-launch-model) ────────────────
  // Флаг `is_launched` разграничивает «операционно запущенные» города (есть
  // мастера, полный опыт маркетплейса) и «пре-лонч/SEO» города (страницы копят
  // вес, но каталог/заявки не открыты). Аддитивно и идемпотентно.
  //
  // Краснодар — единственный запущенный город на момент написания. Ставим ему
  // is_launched=true безусловно (idempotent), чтобы флагманский город никогда
  // случайно не «схлопнулся» в 404 из-за дефолта false. Остальные города
  // управляются через БД (переключаются по факту масштабирования).
  // Зеркало: artifacts/api-server/migrations/2026-07-19-city-launch-model.sql.
  await db.execute(sql.raw(`
ALTER TABLE cities ADD COLUMN IF NOT EXISTS is_launched boolean NOT NULL DEFAULT false;
UPDATE cities SET is_launched = true WHERE slug = 'krasnodar';
  `));

  // ── Real Price — Объект(смета)→страница→агрегат цен (spec: .kiro/specs/real-price) ──
  // Фаза 0: словарь видов работ + расширение receipts до «Объекта» + таблица
  // нормализованных ценовых точек. Аддитивно и идемпотентно; существующий
  // receipt-флоу (оплата/подтверждение, /receipt/:token, paymentState) не трогаем.
  // Схемы: lib/db/src/schema/{work-types,price-points,receipts}.ts.
  // Зеркало: artifacts/api-server/migrations/2026-07-20-real-price-baseline.sql.
  await db.execute(sql.raw(`
CREATE TABLE IF NOT EXISTS work_types (
  id serial PRIMARY KEY,
  slug varchar(120) NOT NULL,
  name text NOT NULL,
  category varchar(16) NOT NULL DEFAULT 'project',
  default_unit varchar(24),
  synonyms text[] NOT NULL DEFAULT '{}',
  service_type_id integer REFERENCES service_types(id) ON DELETE SET NULL,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS work_types_slug_key ON work_types(slug);

ALTER TABLE receipts
  ADD COLUMN IF NOT EXISTS object_type     varchar(16),
  ADD COLUMN IF NOT EXISTS source          varchar(16) NOT NULL DEFAULT 'platform',
  ADD COLUMN IF NOT EXISTS area            numeric(10,2),
  ADD COLUMN IF NOT EXISTS zhk             varchar(160),
  ADD COLUMN IF NOT EXISTS stages          jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS is_published    boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS published_at    timestamp,
  ADD COLUMN IF NOT EXISTS is_indexable    boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS publish_consent boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS slug            varchar(120),
  ADD COLUMN IF NOT EXISTS seo_title       varchar(70),
  ADD COLUMN IF NOT EXISTS seo_description varchar(180),
  ADD COLUMN IF NOT EXISTS public_title    varchar(150);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'receipts_slug_key') THEN
    ALTER TABLE receipts ADD CONSTRAINT receipts_slug_key UNIQUE (slug);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS price_points (
  id serial PRIMARY KEY,
  order_id integer NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  receipt_id integer REFERENCES receipts(id) ON DELETE SET NULL,
  master_id integer REFERENCES masters(id),
  work_type_id integer NOT NULL REFERENCES work_types(id),
  unit varchar(24),
  quantity numeric(12,2),
  unit_price numeric(12,2) NOT NULL,
  total numeric(12,2),
  city text,
  district text,
  zhk varchar(160),
  source varchar(16) NOT NULL DEFAULT 'platform',
  closed_at timestamp,
  created_at timestamp NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS price_points_work_city_idx ON price_points(work_type_id, city, closed_at);
CREATE INDEX IF NOT EXISTS price_points_work_district_idx ON price_points(work_type_id, district);
  `));

  // Стартовый словарь видов работ (Real Price). Идемпотентно (ON CONFLICT slug
  // DO NOTHING). category: 'project'|'task' — headline-типы для маршрутизации
  // Объекта; 'work' — гранулярные позиции сметы (для агрегации цен). synonyms —
  // стемы для последующего маппинга свободных описаний позиций. Набор — стартовый,
  // курируется дальше в CRM.
  await db.execute(sql.raw(`
INSERT INTO work_types (slug, name, category, default_unit, synonyms, sort_order) VALUES
  ('demontazh','Демонтаж','work','м²',ARRAY['демонтаж','снятие','обдирка'],10),
  ('shtukaturka-sten','Штукатурка стен','work','м²',ARRAY['штукатур'],20),
  ('shpaklevka-sten','Шпаклёвка стен','work','м²',ARRAY['шпакл','шпаклёвк','шпаклевк','шпаклеван'],30),
  ('gruntovka','Грунтовка','work','м²',ARRAY['грунт'],40),
  ('shlifovka','Шлифовка стен','work','м²',ARRAY['шлифов'],50),
  ('pokraska-sten','Покраска стен','work','м²',ARRAY['покраск','окраск'],60),
  ('pokraska-potolka','Покраска потолка','work','м²',ARRAY['покраска потолк','потолок покрас'],70),
  ('poklejka-oboev','Поклейка обоев','work','м²',ARRAY['обои','обоев','поклейк'],80),
  ('stekloholst','Стеклохолст / малярный флизелин','work','м²',ARRAY['стеклохолст','стеклохост'],90),
  ('styazhka-pola','Стяжка пола','work','м²',ARRAY['стяжк'],100),
  ('ukladka-plitki-steny','Укладка плитки на стены','work','м²',ARRAY['плитк','настенн плитк','укладка плитки'],110),
  ('ukladka-plitki-pol','Укладка керамогранита на пол','work','м²',ARRAY['керамогранит','плитки на пол','напольн плитк'],120),
  ('zatirka-shvov','Затирка швов','work','м²',ARRAY['затирк','оформление швов'],130),
  ('ukladka-laminata','Укладка ламината','work','м²',ARRAY['ламинат'],140),
  ('shtroblenie','Штробление стен','work','м.п.',ARRAY['штроб'],150),
  ('montazh-gkl','Короба и перегородки ГКЛ','work','м²',ARRAY['гкл','гипсокартон','короб'],160),
  ('otkosy','Откосы','work','шт',ARRAY['откос'],170),
  ('plintus','Плинтус','work','м.п.',ARRAY['плинтус'],180),
  ('elektrika','Электромонтаж (розетки, разводка)','work','точка',ARRAY['электрик','розет','выключател','проводк','щит'],190),
  ('santehnika-razvodka','Разводка сантехники','work','точка',ARRAY['разводка труб','канализац','водоснабж','разводка воды'],200),
  ('ustanovka-santehniki','Установка сантехприборов','work','шт',ARRAY['унитаз','раковин','смесител','ванн','тумб','вытяжк','люк'],210),
  ('tech-otverstiya','Технические отверстия / коронование','work','шт',ARRAY['коронован','тех.отверст','отверстия'],220),
  ('sanuzel-pod-klyuch','Санузел под ключ','project','объект',ARRAY['санузел под ключ','ванная под ключ','сан.узел','с/у под ключ'],300),
  ('kuhnya-pod-klyuch','Кухня под ключ','project','объект',ARRAY['кухня под ключ'],310),
  ('kvartira-pod-klyuch','Квартира под ключ','project','объект',ARRAY['квартира под ключ','комплексн отделк','ремонт под ключ'],320),
  ('zamena-smesitelya','Замена смесителя','task','шт',ARRAY['замена смесител'],400),
  ('zamena-zamka','Замена замка','task','шт',ARRAY['замена замка'],410),
  ('naveska-sborka','Навеска и сборка','task','шт',ARRAY['навеск','сборк','повесить'],420),
  ('melkiy-remont','Мелкий ремонт (муж на час)','task','час',ARRAY['муж на час','мелкий ремонт'],430)
ON CONFLICT (slug) DO NOTHING;
  `));

  // Real Price — витрина агрегатов цен (Фаза 1). Идемпотентно.
  // Зеркало: artifacts/api-server/migrations/2026-07-20-real-price-aggregates.sql.
  await db.execute(sql.raw(`
CREATE TABLE IF NOT EXISTS price_aggregates (
  id serial PRIMARY KEY,
  key_type varchar(16) NOT NULL,
  work_type_id integer NOT NULL REFERENCES work_types(id) ON DELETE CASCADE,
  city text NOT NULL DEFAULT '',
  district text NOT NULL DEFAULT '',
  unit varchar(24),
  p25 numeric(12,2),
  p50 numeric(12,2),
  p75 numeric(12,2),
  n integer NOT NULL DEFAULT 0,
  series_12m jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_indexable boolean NOT NULL DEFAULT false,
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS price_aggregates_key_uidx ON price_aggregates(key_type, work_type_id, city, district);
  `));

  console.log("[startup] Runtime fixes applied");
}

/**
 * Идемпотентный DDL гео-сообщества «ХочуТакже». Выделен в отдельную функцию,
 * т.к. содержит `DO $$ ... $$` блоки и должен исполняться как единый simple-query
 * (без bind-параметров). Зеркалит миграцию 2026-01-20-community-baseline.sql.
 */
async function applyCommunityBaseline() {
  await db.execute(sql.raw(`
-- 1. cities — стартовые города и SEO-покрытие
ALTER TABLE cities
  ADD COLUMN IF NOT EXISTS is_starter     boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_geo_covered boolean NOT NULL DEFAULT false;

-- 2. community_accounts (создаётся до zhk; циркулярный FK добавляется ниже)
CREATE TABLE IF NOT EXISTS community_accounts (
  id                serial PRIMARY KEY,
  phone             varchar(30) NOT NULL,
  phone_verified_at timestamp,
  role              varchar(20) NOT NULL DEFAULT 'resident',
  zhk_id            integer,
  max_user_id       varchar(80),
  created_at        timestamp   NOT NULL DEFAULT NOW(),
  CONSTRAINT community_accounts_phone_key UNIQUE (phone)
);
CREATE INDEX IF NOT EXISTS community_accounts_zhk_idx      ON community_accounts (zhk_id);
CREATE INDEX IF NOT EXISTS community_accounts_max_user_idx ON community_accounts (max_user_id);

-- 3. zhk
CREATE TABLE IF NOT EXISTS zhk (
  id                    serial PRIMARY KEY,
  slug                  varchar(100) NOT NULL,
  name                  varchar(100) NOT NULL,
  name_normalized       varchar(100) NOT NULL,
  city_id               integer      NOT NULL REFERENCES cities(id) ON DELETE CASCADE,
  developer             varchar(200),
  completion_date       varchar(40),
  buildings             jsonb,
  status                varchar(20)  NOT NULL DEFAULT 'NON_LIVING',
  is_seeded             boolean      NOT NULL DEFAULT false,
  content_score         integer      NOT NULL DEFAULT 0,
  is_indexable          boolean      NOT NULL DEFAULT false,
  created_by_account_id integer      REFERENCES community_accounts(id) ON DELETE SET NULL,
  seo_title             varchar(70),
  seo_description       varchar(180),
  h1                    varchar(100),
  body_md               text,
  created_at            timestamp    NOT NULL DEFAULT NOW(),
  CONSTRAINT zhk_slug_key UNIQUE (slug)
);
CREATE INDEX IF NOT EXISTS zhk_city_name_normalized_idx ON zhk (city_id, name_normalized);
CREATE INDEX IF NOT EXISTS zhk_city_status_idx          ON zhk (city_id, status);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'community_accounts_zhk_id_fkey'
      AND table_name = 'community_accounts'
  ) THEN
    ALTER TABLE community_accounts
      ADD CONSTRAINT community_accounts_zhk_id_fkey
      FOREIGN KEY (zhk_id) REFERENCES zhk(id) ON DELETE SET NULL;
  END IF;
END $$;

-- 4. specialties
CREATE TABLE IF NOT EXISTS specialties (
  id         serial PRIMARY KEY,
  slug       varchar(100) NOT NULL,
  name       varchar(100) NOT NULL,
  is_active  boolean      NOT NULL DEFAULT true,
  created_at timestamp    NOT NULL DEFAULT NOW(),
  CONSTRAINT specialties_slug_key UNIQUE (slug)
);

-- 5. pro_memberships
CREATE TABLE IF NOT EXISTS pro_memberships (
  id           serial PRIMARY KEY,
  account_id   integer   NOT NULL REFERENCES community_accounts(id) ON DELETE CASCADE,
  specialty_id integer   REFERENCES specialties(id) ON DELETE SET NULL,
  verified     boolean   NOT NULL DEFAULT false,
  verified_at  timestamp,
  created_at   timestamp NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS pro_memberships_account_idx   ON pro_memberships (account_id);
CREATE INDEX IF NOT EXISTS pro_memberships_specialty_idx ON pro_memberships (specialty_id);

-- 6. community_threads
CREATE TABLE IF NOT EXISTS community_threads (
  id                serial PRIMARY KEY,
  zone              varchar(20)  NOT NULL,
  scope             varchar(10)  NOT NULL,
  city_id           integer      REFERENCES cities(id) ON DELETE SET NULL,
  zhk_id            integer      REFERENCES zhk(id) ON DELETE CASCADE,
  specialty_id      integer      REFERENCES specialties(id) ON DELETE SET NULL,
  is_local          boolean      NOT NULL DEFAULT false,
  category          varchar(40),
  title             varchar(200) NOT NULL,
  body              text         NOT NULL,
  author_account_id integer      REFERENCES community_accounts(id) ON DELETE SET NULL,
  is_seeded         boolean      NOT NULL DEFAULT false,
  visibility        varchar(12)  NOT NULL DEFAULT 'public',
  moderation_status varchar(16)  NOT NULL DEFAULT 'not_screened',
  last_activity_at  timestamp    NOT NULL DEFAULT NOW(),
  created_at        timestamp    NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS community_threads_scope_city_created_idx
  ON community_threads (scope, city_id, created_at);
CREATE INDEX IF NOT EXISTS community_threads_scope_zhk_created_idx
  ON community_threads (scope, zhk_id, created_at);
CREATE INDEX IF NOT EXISTS community_threads_zone_specialty_local_city_idx
  ON community_threads (zone, specialty_id, is_local, city_id);
CREATE INDEX IF NOT EXISTS community_threads_zone_city_idx  ON community_threads (zone, city_id);
CREATE INDEX IF NOT EXISTS community_threads_zhk_idx        ON community_threads (zhk_id);
CREATE INDEX IF NOT EXISTS community_threads_specialty_idx  ON community_threads (specialty_id);

-- 7. community_thread_drafts
CREATE TABLE IF NOT EXISTS community_thread_drafts (
  id                serial PRIMARY KEY,
  author_account_id integer   REFERENCES community_accounts(id) ON DELETE SET NULL,
  payload           jsonb     NOT NULL,
  reason            varchar(40),
  created_at        timestamp NOT NULL DEFAULT NOW()
);

-- 8. community_moderation_log
CREATE TABLE IF NOT EXISTS community_moderation_log (
  id           serial PRIMARY KEY,
  target_type  varchar(20) NOT NULL,
  target_id    integer     NOT NULL,
  action       varchar(24) NOT NULL,
  reason       text,
  moderator_id integer,
  created_at   timestamp   NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS community_moderation_log_target_idx
  ON community_moderation_log (target_type, target_id);

-- 9. zhk_weekly_activity
CREATE TABLE IF NOT EXISTS zhk_weekly_activity (
  id               serial PRIMARY KEY,
  zhk_id           integer NOT NULL REFERENCES zhk(id) ON DELETE CASCADE,
  week_start       date    NOT NULL,
  active_residents integer NOT NULL DEFAULT 0,
  created_at       timestamp NOT NULL DEFAULT NOW(),
  updated_at       timestamp NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS zhk_weekly_activity_zhk_week_key
  ON zhk_weekly_activity (zhk_id, week_start);
CREATE INDEX IF NOT EXISTS zhk_weekly_activity_zhk_idx
  ON zhk_weekly_activity (zhk_id);

-- 10. community_comments (форум-слой: комментарии/ответы к темам)
CREATE TABLE IF NOT EXISTS community_comments (
  id                serial PRIMARY KEY,
  thread_id         integer NOT NULL REFERENCES community_threads(id) ON DELETE CASCADE,
  parent_comment_id integer REFERENCES community_comments(id) ON DELETE CASCADE,
  author_account_id integer REFERENCES community_accounts(id) ON DELETE SET NULL,
  body              text        NOT NULL,
  is_seeded         boolean     NOT NULL DEFAULT false,
  visibility        varchar(12) NOT NULL DEFAULT 'public',
  moderation_status varchar(16) NOT NULL DEFAULT 'not_screened',
  created_at        timestamp   NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS community_comments_thread_created_idx
  ON community_comments (thread_id, created_at);
CREATE INDEX IF NOT EXISTS community_comments_parent_idx
  ON community_comments (parent_comment_id);
  `));
  console.log("[startup] Community baseline schema ensured");
}

// Seed default voronka columns if they don't exist yet.
// Safe to run on every startup — checks before inserting.
async function seedVoronkaColumns() {
  const DEFAULT_COLUMNS = [
    { name: "Новые",           position: 1, receivesOrders: false, color: "blue"   },
    { name: "Свободен",        position: 2, receivesOrders: true,  color: "green"  },
    { name: "Занят",           position: 3, receivesOrders: false, color: "yellow" },
    { name: "На объекте",      position: 4, receivesOrders: true,  color: "orange" },
    { name: "Ожидает оплаты",  position: 5, receivesOrders: false, color: "red"    },
    { name: "Отстраненные",    position: 6, receivesOrders: false, color: "grey"   },
  ];

  const existing = await db.select().from(voronkaColumnsTable);
  const existingNames = existing.map(c => c.name);

  // Rename "Свободные" → "Свободен" if present (typo fix from initial setup)
  const svobodnyeCol = existing.find(c => c.name === "Свободные");
  if (svobodnyeCol) {
    await db.update(voronkaColumnsTable)
      .set({ name: "Свободен", receivesOrders: true, position: 2 })
      .where(eq(voronkaColumnsTable.id, svobodnyeCol.id));
    console.log("[startup] Renamed 'Свободные' → 'Свободен'");
    existingNames[existingNames.indexOf("Свободные")] = "Свободен";
  }

  for (const col of DEFAULT_COLUMNS) {
    if (!existingNames.includes(col.name)) {
      await db.insert(voronkaColumnsTable).values(col);
      console.log(`[startup] Created voronka column: '${col.name}'`);
    }
  }

  // After ensuring "Занят" exists, fix positions and receivesOrders of subsequent columns
  const afterInsert = await db.select().from(voronkaColumnsTable);
  const naObyekteCol = afterInsert.find(c => c.name === "На объекте");
  const ozhidaetCol = afterInsert.find(c => c.name === "Ожидает оплаты");
  const zanyatCol = afterInsert.find(c => c.name === "Занят");
  if (zanyatCol) {
    if (naObyekteCol && naObyekteCol.position !== 4) {
      await db.update(voronkaColumnsTable).set({ position: 4 }).where(eq(voronkaColumnsTable.id, naObyekteCol.id));
      console.log("[startup] Updated 'На объекте' position → 4");
    }
    if (ozhidaetCol && ozhidaetCol.position !== 5) {
      await db.update(voronkaColumnsTable).set({ position: 5 }).where(eq(voronkaColumnsTable.id, ozhidaetCol.id));
      console.log("[startup] Updated 'Ожидает оплаты' position → 5");
    }
    // "Занят" = manual offline (left the line), must NOT receive dispatches
    if (zanyatCol.receivesOrders) {
      await db.update(voronkaColumnsTable).set({ receivesOrders: false }).where(eq(voronkaColumnsTable.id, zanyatCol.id));
      console.log("[startup] Updated 'Занят' receivesOrders → false");
    }
    // "На объекте" = working, CAN receive dispatches (limit enforced by eligibility check)
    if (naObyekteCol && !naObyekteCol.receivesOrders) {
      await db.update(voronkaColumnsTable).set({ receivesOrders: true }).where(eq(voronkaColumnsTable.id, naObyekteCol.id));
      console.log("[startup] Updated 'На объекте' receivesOrders → true");
    }
  }
}

// Token packages, service prices and rules seeders removed — token model dropped (Phase C cleanup).
// One-time migration: active masters who existed before the admin-confirmation requirement
// should be granted passportVerified=true so they are not blocked retroactively.
async function grantPassportVerifiedToActiveMasters() {
  const updated = await db.update(mastersTable)
    .set({ passportVerified: true })
    .where(
      sql`status = 'active' AND (passport_verified IS FALSE OR passport_verified IS NULL)`
    );
  const count = (updated as any).rowCount ?? 0;
  if (count > 0) {
    console.log(`[startup] Granted passportVerified=true to ${count} existing active master(s)`);
  }
}

// Auto-expire dispatch records that have been in "sent" status for more than 24 hours.
// These masters didn't respond — mark them "rejected" so they're excluded from future re-broadcasts.
async function autoExpireDispatches() {
  const cutoff = new Date(Date.now() - 24 * 60 * 60 * 1000);
  const result = await db.update(orderDispatchesTable)
    .set({ status: "rejected" })
    .where(and(eq(orderDispatchesTable.status, "sent"), lte(orderDispatchesTable.createdAt, cutoff)))
    .returning({ id: orderDispatchesTable.id });
  if (result.length > 0) {
    console.log(`[auto-expire] Expired ${result.length} dispatch record(s) older than 24h`);
  }
}

// Auto-broadcast scheduled orders: if an order has scheduledAt within the next 4 hours
// and has never been dispatched, trigger broadcast automatically.
async function autoScheduledOrderBroadcast() {
  const now = new Date();
  const in4h = new Date(now.getTime() + 4 * 60 * 60 * 1000);
  const in2h = new Date(now.getTime() + 2 * 60 * 60 * 1000);

  const orders = await db.select().from(ordersTable)
    .where(and(
      eq(ordersTable.status, "waiting_master"),
      eq(ordersTable.dispatchStatus, "none"),
    ));

  const tooBroadcast = orders.filter(o =>
    o.scheduledAt && new Date(o.scheduledAt) >= in2h && new Date(o.scheduledAt) <= in4h
  );

  for (const order of tooBroadcast) {
    try {
      const result = await performBroadcast(order.id);
      if (result.ok) {
        console.log(`[auto-broadcast] Sent to ${result.sent} master(s) for scheduled order #${order.id}`);
      } else {
        console.log(`[auto-broadcast] Skipped order #${order.id}: ${result.error}`);
      }
    } catch (e) {
      console.error(`[auto-broadcast] Error for order #${order.id}:`, e);
    }
  }
}

/**
 * One-time (and periodic) fix: ensure masters with active orders are in "На объекте",
 * and masters with no active orders are in "Свободен". Skips masters in non-receiving
 * columns (e.g. "Занят", "Отстраненные") — those are manually set by operators.
 */
async function recalculateMasterVoronkaColumns() {
  const cols = await db.select().from(voronkaColumnsTable);
  const freeCol = cols.find(c => c.name === "Свободен" && c.receivesOrders) ?? cols.find(c => c.receivesOrders);
  const onSiteCol = cols.find(c => c.name === "На объекте")
    ?? cols.find(c => c.receivesOrders && c.name !== "Свободен");
  if (!freeCol || !onSiteCol) return;

  const activeOrders = await db.select().from(ordersTable)
    .where(inArray(ordersTable.status, ["master_assigned", "in_progress"]));

  const activeCountByMaster = new Map<number, number>();
  for (const o of activeOrders) {
    if (o.masterId) activeCountByMaster.set(o.masterId, (activeCountByMaster.get(o.masterId) ?? 0) + 1);
  }

  const masters = await db.select().from(mastersTable).where(eq(mastersTable.status, "active"));
  let fixed = 0;
  for (const m of masters) {
    const currentCol = cols.find(c => c.id === m.voronkaColumnId);
    const activeCount = activeCountByMaster.get(m.id) ?? 0;

    let correctColId: number | null = null;
    if (activeCount >= 1) {
      // Master has active orders → must be "На объекте" regardless of current column
      correctColId = onSiteCol.id;
    } else if (currentCol?.receivesOrders) {
      // Master is free and currently in a receiving column → ensure "Свободен"
      correctColId = freeCol.id;
    }
    // Masters in non-receiving columns (Занят, Отстраненные) with no active orders → leave them alone

    if (correctColId !== null && m.voronkaColumnId !== correctColId) {
      await db.update(mastersTable).set({ voronkaColumnId: correctColId }).where(eq(mastersTable.id, m.id));
      fixed++;
    }
  }
  if (fixed > 0) console.log(`[voronka-fix] Corrected ${fixed} master(s) to proper column`);
}

// Auto-close orders that have been in "waiting_master" for 48+ hours.
// Uses updatedAt (not createdAt) so the timer resets when an order is returned to the pool.
// Sets status="cancelled", cancelType="no_master_found".
async function autoCloseNoMasterOrders() {
  const cutoff = new Date(Date.now() - 48 * 60 * 60 * 1000);
  const stale = await db.select({ id: ordersTable.id, leadId: ordersTable.leadId })
    .from(ordersTable)
    .where(and(
      eq(ordersTable.status, "waiting_master"),
      lte(ordersTable.updatedAt, cutoff),
      isNull(ordersTable.deletedAt),
    ));

  if (stale.length === 0) return;

  for (const order of stale) {
    await db.update(ordersTable)
      .set({
        status: "cancelled",
        cancelType: "no_master_found",
        cancelReason: "Мастер не найден в течение 48 часов — заказ закрыт автоматически",
        updatedAt: new Date(),
      })
      .where(eq(ordersTable.id, order.id));
  }
  console.log(`[auto-close] Closed ${stale.length} order(s) with no_master_found (>48h waiting_master)`);
}

// Auto re-broadcast orders that have been in "dispatching" for 30+ min with zero responses.
async function autoReBroadcastNoResponse() {
  const cutoff = new Date(Date.now() - 30 * 60 * 1000); // 30 min ago
  const orders = await db.select().from(ordersTable)
    .where(and(
      eq(ordersTable.status, "waiting_master"),
      eq(ordersTable.dispatchStatus, "dispatching"),
    ));

  for (const order of orders) {
    // Only re-broadcast if last broadcast was > 30 min ago
    const lastBroadcast = (order as any).lastBroadcastAt as Date | null;
    if (lastBroadcast && new Date(lastBroadcast) > cutoff) continue;
    // Check if any master has responded
    const dispatches = await db.select().from(orderDispatchesTable)
      .where(and(eq(orderDispatchesTable.orderId, order.id), eq(orderDispatchesTable.status, "responded")));
    if (dispatches.length > 0) continue; // Already has responses, skip
    try {
      const result = await performBroadcast(order.id);
      if (result.ok && result.sent > 0) {
        await db.execute(sql`UPDATE orders SET broadcast_count = COALESCE(broadcast_count, 0) + 1, last_broadcast_at = NOW() WHERE id = ${order.id}`);
        console.log(`[auto-rebroadcast] Re-sent order #${order.id} to ${result.sent} master(s)`);
      }
    } catch (e) {
      console.error(`[auto-rebroadcast] Error for order #${order.id}:`, e);
    }
  }
}

// Apply pending DB schema changes (drizzle migrations) before any code that
// queries the schema. Then apply runtime fixes (constraints/indexes/seeds that
// aren't in the Drizzle schema yet) and kick off the rest of the bootstrap.
runDrizzleMigrations()
  .then(() => runRuntimeFixes())
  .then(() => {
    console.log("--- ADMIN AUTH PREPARED ---");
    bootstrapFirstAdmin().catch(console.error);
    seedVoronkaColumns().catch(console.error);
    grantPassportVerifiedToActiveMasters().catch(console.error);
    recalculateMasterVoronkaColumns().catch(console.error);
    checkOverdueTransactions().catch(console.error);
    autoExpireDispatches().catch(console.error);
    autoCloseNoMasterOrders().catch(console.error);
    initCheckinScheduler().catch(console.error);
    backfillReceiptTransactions()
      .then(n => { if (n > 0) console.log(`[backfill] Created ${n} receipt transactions`); })
      .catch(e => console.error("[backfill] Receipt transactions error:", e));
    // AI-designer background worker — каждые 5s забирает 1 design в status='generating'
    // и обрабатывает (Fal.ai × 4 view + GPT artefacts + color extraction + DB updates).
    import("./lib/designWorker.js").then(({ startDesignWorker }) => {
      startDesignWorker();
    }).catch(e => console.error("[designWorker] failed to load:", e));
    // ── Демо-сид гео-сообщества «ХочуТакже» (по флагу) ──────────────────────
    // Разовое идемпотентное наполнение стартовых городов/ЖК/специальностей и
    // демо-лент, чтобы разделы /goroda, /zhk, /pro выглядели живыми до появления
    // реального контента. Включается COMMUNITY_SEED_ENABLED=true.
    if (process.env.COMMUNITY_SEED_ENABLED === "true") {
      seedCommunityDemo().catch((e) => console.error("[community-seed] failed:", e));
    }
  })
  .catch((err) => {
    console.error("[startup] Migration/bootstrap failed:", err);
    process.exit(1);
  });

// Mark overdue commissions every 6 hours
setInterval(() => checkOverdueTransactions().catch(console.error), 6 * 60 * 60 * 1000);
// Auto-expire dispatches every hour
setInterval(() => autoExpireDispatches().catch(console.error), 60 * 60 * 1000);
// Auto-close orders with no master found after 48h — every hour
setInterval(() => autoCloseNoMasterOrders().catch(console.error), 60 * 60 * 1000);
// Auto-confirm landing lead responses after 96h hold — every hour
setInterval(async () => {
  try {
    await db.execute(sql`
      UPDATE lead_responses
      SET status = 'confirmed', confirmed_at = NOW()
      WHERE status = 'pending'
        AND created_at < NOW() - INTERVAL '96 hours'
    `);
  } catch (e) {
    console.error("[lead-hold] auto-confirm job failed:", e);
  }
}, 60 * 60 * 1000);
// Auto-broadcast scheduled orders 2–4h before scheduledAt
setInterval(() => autoScheduledOrderBroadcast().catch(console.error), 15 * 60 * 1000);
// autoReBroadcastNoResponse removed — per user request
// AI dispatcher: only post-assignment flow (greeting → call check-in → scheduled follow-ups)
setInterval(() => runProactiveChecks().catch(console.error), 30 * 60 * 1000);
// Priority assignment: check expired response windows every 60 seconds
setInterval(() => checkResponseWindows().catch(console.error), 60 * 1000);
console.log("[checkin] Priority assignment scheduler started");

// Operator task escalations: notify admin via MAX about critical-overdue tasks every 5 min
import("./lib/tasksEscalation.js").then(({ runTaskEscalations }) => {
  setInterval(() => runTaskEscalations().catch(console.error), 5 * 60 * 1000);
  console.log("[escalation] Operator task escalation scheduler started (MAX)");
}).catch(err => console.error("[escalation] failed to load module:", err));

// ─── Имитация активности гео-сообщества «ХочуТакже» (по флагу) ───────────────
// Периодически бампает last_activity_at у сид-тем и иногда добавляет свежую
// тему, чтобы ленты выглядели живыми. Работает ТОЛЬКО с is_seeded=true строками.
// Включается COMMUNITY_ACTIVITY_SIM_ENABLED=true; интервал —
// COMMUNITY_ACTIVITY_SIM_INTERVAL_MIN (мин, по умолчанию 30).
if (process.env.COMMUNITY_ACTIVITY_SIM_ENABLED === "true") {
  const simMin = Number(process.env.COMMUNITY_ACTIVITY_SIM_INTERVAL_MIN) || 30;
  const simMs = Math.max(1, simMin) * 60 * 1000;
  setInterval(() => simulateCommunityActivity().catch(console.error), simMs);
  console.log(`[community-activity] simulator started (every ${Math.max(1, simMin)} min)`);
}
// runQuickAutonomousCheck removed — caused spam to masters
// runAutonomousCycle removed — caused spam to masters

// ─── Checkin broadcast scheduler ─────────────────────────────────────────────
// Reads broadcast + reminder times from DB every minute and fires if needed.
// Also fires on startup if today's broadcast hasn't happened yet.

let checkinFiredDate: string | null = null;
let reminderFiredDate: string | null = null;

function getMskTime(): { hhmm: string; today: string } {
  const nowMsk = new Date(Date.now() + 3 * 60 * 60 * 1000);
  const hh = nowMsk.getUTCHours().toString().padStart(2, "0");
  const mm = nowMsk.getUTCMinutes().toString().padStart(2, "0");
  return { hhmm: `${hh}:${mm}`, today: nowMsk.toISOString().split("T")[0] };
}

async function getCheckinSettings() {
  const keys = ["checkin_broadcast_time", "checkin_reminder_time", "checkin_reminder_enabled",
                "checkin_last_broadcast_date", "checkin_last_reminder_date"];
  const rows = await db.select().from(systemSettingsTable).where(inArray(systemSettingsTable.key, keys));
  const get = (k: string, d: string) => rows.find(r => r.key === k)?.value ?? d;
  return {
    broadcastTime:    get("checkin_broadcast_time",      "07:00"),
    reminderTime:     get("checkin_reminder_time",       "12:00"),
    reminderEnabled:  get("checkin_reminder_enabled",    "false") === "true",
    lastBroadcast:    get("checkin_last_broadcast_date", ""),
    lastReminder:     get("checkin_last_reminder_date",  ""),
  };
}

// Startup: restore in-memory fired-date flags from DB so restarts don't double-fire
async function initCheckinScheduler() {
  try {
    const cfg = await getCheckinSettings();
    const { today, hhmm } = getMskTime();

    if (cfg.lastBroadcast === today) {
      checkinFiredDate = today;
      console.log("[checkin] Broadcast already fired today — skipping startup fire");
    } else if (hhmm >= cfg.broadcastTime) {
      // Missed window due to restart — fire now
      checkinFiredDate = today;
      console.log(`[checkin] Missed broadcast (${cfg.broadcastTime} MSK), firing on startup`);
      broadcastCheckin().catch(console.error);
    }

    if (cfg.lastReminder === today) {
      reminderFiredDate = today;
    } else if (cfg.reminderEnabled && hhmm >= cfg.reminderTime && checkinFiredDate === today) {
      reminderFiredDate = today;
      console.log(`[checkin] Missed reminder (${cfg.reminderTime} MSK), firing on startup`);
      broadcastCheckinReminder().catch(console.error);
    }
  } catch (e) {
    console.error("[checkin] initScheduler error:", e);
  }
}

// Auto-mark non-responders as "not ready" at midnight MSK
let midnightAutoCheckinDate: string | null = null;

async function autoCheckinMidnight() {
  try {
    const { today } = getMskTime();
    if (midnightAutoCheckinDate === today) return;

    const yesterday = new Date(Date.now() + 3 * 60 * 60 * 1000);
    yesterday.setDate(yesterday.getDate() - 1);
    const yesterdayStr = yesterday.toISOString().split("T")[0];

    // Mark all null responses for yesterday as "not ready"
    const result = await db.execute(sql`
      UPDATE master_checkins
      SET is_available = false, responded_at = NOW()
      WHERE date = ${yesterdayStr} AND responded_at IS NULL
    `);

    midnightAutoCheckinDate = today;
    console.log(`[checkin] Midnight auto-reset: ${result.rowCount ?? 0} master(s) marked as not ready for ${yesterdayStr}`);
  } catch (e) {
    console.error("[checkin] Midnight auto-reset error:", e);
  }
}

let morningBriefingFiredDate: string | null = null;
let eveningReportFiredDate: string | null = null;
let fridayWeeklySummaryFiredDate: string | null = null;
let monthlyReportFiredDate: string | null = null;
const autonomousCycleFiredHours = new Set<string>(); // "YYYY-MM-DD HH"

setInterval(async () => {
  try {
    const { hhmm, today } = getMskTime();
    const cfg = await getCheckinSettings();

    // Midnight: auto-mark non-responders as "not ready"
    if (hhmm === "00:00") {
      autoCheckinMidnight().catch(console.error);
    }

    if (hhmm === cfg.broadcastTime && checkinFiredDate !== today) {
      checkinFiredDate = today;
      console.log(`[checkin] Firing broadcast at ${hhmm} MSK`);
      broadcastCheckin().catch(console.error);
    }

    if (cfg.reminderEnabled && hhmm === cfg.reminderTime && reminderFiredDate !== today && checkinFiredDate === today) {
      reminderFiredDate = today;
      console.log(`[checkin] Firing reminder at ${hhmm} MSK`);
      broadcastCheckinReminder().catch(console.error);
    }

    // Scheduled scenario runner — check every morning at 09:00 MSK
    if (hhmm === "09:00") {
      (async () => {
        try {
          const result = await db.execute(sql`SELECT value FROM system_settings WHERE key = 'scenario_schedules' LIMIT 1`);
          const row = (result.rows[0] as any);
          if (row) {
            const schedules: Record<string, { enabled: boolean; days: number[] }> = JSON.parse(row.value);
            const nowMskDay = new Date(Date.now() + 3 * 60 * 60 * 1000).getUTCDay();
            for (const [scenarioId, cfg] of Object.entries(schedules)) {
              if (cfg.enabled && cfg.days.includes(nowMskDay)) {
                console.log(`[autonomousAgent] Running scheduled scenario: ${scenarioId}`);
                autonomousAgent.runScenario(scenarioId).catch(e => console.error(`[autonomousAgent] Scheduled scenario error (${scenarioId}):`, e));
              }
            }
          }
        } catch (e) {
          console.error("[autonomousAgent] Schedule check error:", e);
        }
      })();
    }

    // Morning briefing to manager bot at 09:00 MSK
    if (hhmm === "09:00" && morningBriefingFiredDate !== today) {
      morningBriefingFiredDate = today;
      console.log("[managerBot] Firing morning briefing at 09:00 MSK");
      sendMorningBriefing().catch(console.error);

      // Weekly report on Monday
      const nowMsk = new Date(Date.now() + 3 * 60 * 60 * 1000);
      if (nowMsk.getUTCDay() === 1) {
        console.log("[managerBot] Monday — firing weekly report");
        sendWeeklyReport().catch(console.error);
      }

      // First autonomous cycle of the day
      setTimeout(() => runAutonomousCycle("утренняя проверка после брифинга").catch(console.error), 2 * 60 * 1000);
    }

    // Evening summary at 19:00 MSK
    if (hhmm === "19:00" && eveningReportFiredDate !== today) {
      eveningReportFiredDate = today;
      console.log("[managerBot] Firing evening autonomous cycle at 19:00 MSK");
      runAutonomousCycle("вечерняя проверка — итоги дня").catch(console.error);
    }

    // Friday weekly full summary at 18:00 MSK (day 5 = Friday)
    const nowMskWeek = new Date(Date.now() + 3 * 60 * 60 * 1000);
    if (hhmm === "18:00" && nowMskWeek.getUTCDay() === 5 && fridayWeeklySummaryFiredDate !== today) {
      fridayWeeklySummaryFiredDate = today;
      console.log("[managerBot] Friday 18:00 — full weekly autonomous cycle");
      runAutonomousCycle("пятничный итог недели — полная аналитика: топ мастеров, топ услуг, города, финансы").catch(console.error);
    }

    // Monthly report on 1st of month at 10:00 MSK
    const nowMskMonth = new Date(Date.now() + 3 * 60 * 60 * 1000);
    if (hhmm === "10:00" && nowMskMonth.getUTCDate() === 1 && monthlyReportFiredDate !== today) {
      monthlyReportFiredDate = today;
      console.log("[managerBot] 1st of month 10:00 — monthly autonomous cycle");
      runAutonomousCycle("ежемесячный отчёт — первое число месяца: итоги месяца, рейтинг мастеров, финансы, планы на месяц").catch(console.error);
    }

    // Autonomous cycle at 12:00 and 15:00 MSK
    const autoHours = ["12:00", "15:00"];
    for (const slot of autoHours) {
      const slotKey = `${today} ${slot}`;
      if (hhmm === slot && !autonomousCycleFiredHours.has(slotKey)) {
        autonomousCycleFiredHours.add(slotKey);
        console.log(`[autonomousAgent] Firing scheduled cycle at ${slot} MSK`);
        runAutonomousCycle(`плановая проверка ${slot} МСК`).catch(console.error);
      }
    }

  } catch (e) {
    console.error("[checkin] scheduler error:", e);
  }
}, 60 * 1000);
console.log("[checkin] Dynamic broadcast scheduler started");

// ─── Avito item schedule: 08:00 activate, 20:00 deactivate (MSK = UTC+3) ────
let avitoScheduleActivateDate: string | null = null;
let avitoScheduleDeactivateDate: string | null = null;

// On startup — catch up missed windows
(async () => {
  try {
    const { hhmm, today } = getMskTime();
    if (hhmm >= "08:00" && hhmm < "20:00") {
      avitoScheduleActivateDate = today; // mark as if we've activated today
      console.log(`[avito:schedule] Startup: activate window already passed (${hhmm} MSK), marking activated`);
    }
    if (hhmm >= "20:00") {
      avitoScheduleDeactivateDate = today;
      console.log(`[avito:schedule] Startup: deactivate window already passed (${hhmm} MSK), marking deactivated`);
    }
  } catch (e) {
    console.error("[avito:schedule] startup check error:", e);
  }
})();

setInterval(async () => {
  try {
    const { hhmm, today } = getMskTime();

    if (hhmm >= "08:00" && avitoScheduleActivateDate !== today) {
      avitoScheduleActivateDate = today;
      console.log(`[avito:schedule] 08:00 trigger — activating scheduled items`);
      runAvitoSchedule("activate").catch(console.error);
    }

    if (hhmm >= "20:00" && avitoScheduleDeactivateDate !== today) {
      avitoScheduleDeactivateDate = today;
      console.log(`[avito:schedule] 20:00 trigger — deactivating scheduled items`);
      runAvitoSchedule("deactivate").catch(console.error);
    }
  } catch (e) {
    console.error("[avito:schedule] interval error:", e);
  }
}, 60 * 1000); // check every minute
console.log("[avito:schedule] Avito item schedule watcher started (08:00 on / 20:00 off MSK)");

// ─── Template Scenario Schedulers ────────────────────────────────────────────

// Helper to get scenario auto_enabled from DB
async function isScenarioAutoEnabled(scenario: string): Promise<boolean> {
  try {
    const r = await db.execute(sql`SELECT auto_enabled FROM scenario_settings WHERE scenario = ${scenario}`);
    return !!(r.rows[0] as any)?.auto_enabled;
  } catch { return false; }
}

// Scenario 1: broadcast-orders — every 15 min if enabled
setInterval(async () => {
  try {
    if (await isScenarioAutoEnabled("broadcast-orders")) {
      console.log("[scenarios] auto: broadcast-orders");
      runTemplateScenario("broadcast-orders", "auto").catch(console.error);
    }
  } catch (e) { console.error("[scenarios] broadcast-orders interval error:", e); }
}, 15 * 60 * 1000);

// Scenarios 2, 3, 4 — time-based, checked every minute using existing getMskTime helper
let scenarioDiagDate: string | null = null;
let scenarioPriceDate: string | null = null;
const scenarioPaymentFiredHours = new Set<string>();

setInterval(async () => {
  try {
    const { hhmm, today } = getMskTime();
    const nowMsk = new Date(Date.now() + 3 * 60 * 60 * 1000);

    // Scenario 2: payment-reminders + orders-without-receipts at 9:00, 15:00, 21:00 MSK
    for (const slot of ["09:00", "15:00", "21:00"]) {
      const key = `${today} ${slot}`;
      if (hhmm === slot && !scenarioPaymentFiredHours.has(key)) {
        scenarioPaymentFiredHours.add(key);
        if (await isScenarioAutoEnabled("payment-reminders")) {
          console.log(`[scenarios] auto: payment-reminders at ${slot}`);
          runTemplateScenario("payment-reminders", "auto").catch(console.error);
        }
        if (await isScenarioAutoEnabled("orders-without-receipts")) {
          console.log(`[scenarios] auto: orders-without-receipts at ${slot}`);
          runTemplateScenario("orders-without-receipts", "auto").catch(console.error);
        }
      }
    }

    // Scenario 3: order-diagnostics daily at 9:00 MSK
    if (hhmm === "09:00" && scenarioDiagDate !== today) {
      scenarioDiagDate = today;
      if (await isScenarioAutoEnabled("order-diagnostics")) {
        console.log("[scenarios] auto: order-diagnostics");
        runTemplateScenario("order-diagnostics", "auto").catch(console.error);
      }
    }

    // Scenario 4: price-analysis every Monday at 8:00 MSK
    if (hhmm === "08:00" && nowMsk.getUTCDay() === 1 && scenarioPriceDate !== today) {
      scenarioPriceDate = today;
      if (await isScenarioAutoEnabled("price-analysis")) {
        console.log("[scenarios] auto: price-analysis");
        runTemplateScenario("price-analysis", "auto").catch(console.error);
      }
    }
  } catch (e) { console.error("[scenarios] scheduler error:", e); }
}, 60 * 1000);
console.log("[scenarios] Template scenario schedulers started");

// ─── Stuck-orders daily master reminder ──────────────────────────────────────
// Spec: .kiro/specs/stuck-orders-and-master-banner (R8)
// Sends one aggregated push per master at 10:00 MSK if they have any
// non-snoozed pending stuck-orders actions.
let stuckOrdersReminderDate: string | null = null;
setInterval(async () => {
  try {
    const { hhmm, today } = getMskTime();
    if (hhmm === "10:00" && stuckOrdersReminderDate !== today) {
      stuckOrdersReminderDate = today;
      console.log("[stuck-orders] firing daily master reminder");
      const { dailyMasterReminder } = await import("./lib/dailyMasterReminderCron.js");
      dailyMasterReminder().catch(console.error);
    }
  } catch (e) { console.error("[stuck-orders] scheduler error:", e); }
}, 60 * 1000);
console.log("[stuck-orders] Daily master reminder scheduler started (10:00 MSK)");

const server = app.listen(port, "0.0.0.0", () => {
  console.log(`Server listening on port ${port}`);
});

// Graceful shutdown on Railway rolling-restart (SIGTERM) and Ctrl+C (SIGINT).
// Stop accepting new connections, drain in-flight requests, then close the
// PG pool so the new container can start cleanly. Forced exit after 10s
// guards against hanging connections.
let shuttingDown = false;
async function shutdown(signal: NodeJS.Signals) {
  if (shuttingDown) return;
  shuttingDown = true;
  console.log(`[shutdown] ${signal} received, draining…`);

  const forceTimer = setTimeout(() => {
    console.error("[shutdown] grace period exceeded, forcing exit");
    process.exit(1);
  }, 10_000);
  forceTimer.unref();

  server.close((err) => {
    if (err) console.error("[shutdown] server.close error:", err);
    pool.end()
      .then(() => {
        console.log("[shutdown] clean exit");
        process.exit(0);
      })
      .catch((poolErr) => {
        console.error("[shutdown] pool.end error:", poolErr);
        process.exit(1);
      });
  });
}

process.on("SIGTERM", () => { void shutdown("SIGTERM"); });
process.on("SIGINT",  () => { void shutdown("SIGINT");  });
